# Generated by Django 3.0.6 on 2020-05-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projects_git'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='git',
            field=models.URLField(default='https://github.com/Kai-Eiji'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(default='https://github.com/Kai-Eiji'),
        ),
    ]
