# Generated by Django 3.0.6 on 2020-05-18 23:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/files/'), upload_to=''),
        ),
    ]
